name: .NET Core Desktop

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Install Visual C++ Build Tools 14 (MSVC v143)
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: 17.8
        msbuild-architecture: x64
        install-vc-build-tools: true
      
    - name: Restore FufuLauncher
      run: msbuild FufuLauncher\FufuLauncher.csproj /t:Restore /p:Configuration=Release /p:Platform="x64"

    - name: Build FufuLauncher
      run: msbuild FufuLauncher\FufuLauncher.csproj /p:Configuration=Release /p:Platform="x64" /m

    - name: Publish UpdateFufuLauncher
      run: >
        dotnet publish UpdateFufuLauncher\UpdateFufuLauncher.csproj 
        -c Release 
        -r win-x64 
        --self-contained false 
        -p:PublishSingleFile=true 
        -p:IncludeNativeLibrariesForSelfExtract=true 
        -p:IncludeAllContentForSelfExtract=true

    - name: Move UpdateFufuLauncher Output to FufuLauncher Build Directory
      run: |
        $sourcePath = "UpdateFufuLauncher\bin\Release\net8.0-windows\win-x64\publish\*"
        $destPath = "FufuLauncher\bin\x64\Release\net8.0-windows10.0.26100.0"
        
        if (-Not (Test-Path $destPath)) {
            New-Item -ItemType Directory -Force -Path $destPath
        }
        
        Copy-Item -Path $sourcePath -Destination $destPath -Recurse -Force

    - name: Build Installer with Inno Setup
      run: '& "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe" "FufuLauncher.Installer\setup.iss"'

    - name: Upload Installer Artifact
      uses: actions/upload-artifact@v4
      with:
        name: FufuLauncher_Installer
        path: FufuLauncher.Installer\Output\
